# Jupyter usage

## Heading

`Markdown`

Cell type 有 Code Markdown RawNBConvert Heading，不要只是输入代码。

双击代码可以查看


When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

# Numpy usage

多维数组 ndarray；效率更高的数学运算；线性代数运算；傅立叶变换；随机数生成；C/C++/Fortran代码集成；算法间传递数据的容器

## create ndarray
see https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

In [1]:
import numpy as np

In [2]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[  0.00000000e+000,   2.17697548e-314],
       [  0.00000000e+000,   2.12269668e-314]])

In [3]:
np.ndarray((2,), buffer=np.array([1,2,3]),
               offset=np.int_().itemsize,
               dtype=int) # offset = 1*itemsize, i.e. skip first element

array([2, 3])

In [4]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [5]:
x.T

array([[ 1.,  3.],
       [ 2.,  4.]])